apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  DB_USER: Zmxhc2t1c2Vy         # base64 for flaskuser
  DB_PASSWORD: cGFzc3dvcmQ=     # base64 for password
  DB_NAME: Zmxhc2tkYg==         # base64 for flaskdb