apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: default
type: Opaque
data:
  DB_USER: Zmxhc2t1c2Vy        # base64 for "flaskuser"
  DB_PASSWORD: Zmxhc2twYXNz    # base64 for "flaskpass"
  DB_NAME: Zmxhc2tkYg==        # base64 for "flaskdb"
  POSTGRES_PASSWORD: Zmxhc2twYXNz  # base64 for "flaskpass"
