name: CD - Deploy to Minikube

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV

      - name: Update Kubernetes manifests
        run: |
          (Get-Content k8s/deployment.yaml) -replace "ghcr.io/dipankaradhikary/flask-app:.*", "ghcr.io/dipankaradhikary/flask-app:${env:IMAGE_TAG}" | Set-Content k8s/deployment.yaml

      - name: Apply Kubernetes Configs
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
