name: CD - Deploy to Minikube

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        shell: powershell
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "IMAGE_TAG=${{ github.event.workflow_run.head_sha }}"



      - name: Update Kubernetes manifests
        shell: powershell
        run: |
          $deploymentPath = "k8s/deployment.yaml"
          $imageTag = $env:IMAGE_TAG
          $newImage = "ghcr.io/dipankaradhikary/flask-app:$imageTag"
          (Get-Content $deploymentPath) -replace "ghcr.io/dipankaradhikary/flask-app:.*", $newImage | Set-Content $deploymentPath

      - name: Debug deployment.yaml
        shell: powershell
        run: Get-Content k8s/deployment.yaml

      - name: Apply Kubernetes Configs
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml